services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - blog-network

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FE_DOMAIN=http://localhost:8000
      - BE_DOMAIN=http://localhost:5000
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PASSWORD=Mongo123!
      - DB_PORT=27017
      - DB_NAME=blog
    depends_on:
      - mongo
    networks:
      - blog-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo123!
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
