services:
  nextjs:
    container_name: nextjs
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"

  express:
    container_name: express
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo123!

volumes:
  mongo_data:
    driver: local
